#!/usr/bin/env bash
# Unit tests for kc-prompt-match.sh (UserPromptSubmit hook)
#
# Usage: bash test/test-kc-prompt-match.sh
# Run from the knowledge-curator/ directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK="$SCRIPT_DIR/../hooks/kc-prompt-match.sh"

PASS=0
FAIL=0

pass() { echo "  ✓ $1"; PASS=$((PASS + 1)); }
fail() { echo "  ✗ $1"; FAIL=$((FAIL + 1)); }

setup() {
  TEST_DIR=$(mktemp -d)
}

teardown() {
  rm -rf "$TEST_DIR"
}

# ── Test: no knowledge/ directory → silent exit 0 ───────────────────

setup
cd "$TEST_DIR"
OUTPUT=$(echo "some query about database" | "$HOOK" 2>&1); RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "No knowledge dir: exits 0 with no output (fail-open)"
else
  fail "No knowledge dir: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: matching term → emits context block ───────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 5 | 1 | 1 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres for primary store | active | p1 | 2026-07-01 | database, architecture |
| KC-0002 | discovery | Memory leak in connection pool | active | p1 | 2026-06-28 | bug, performance |
| KC-0003 | lesson | Always set statement_timeout | active | p2 | 2026-06-15 | postgres, reliability |
EOF
cd "$TEST_DIR"
# Prompt contains "database" which should match KC-0001's tags
OUTPUT=$(echo "how do we handle the database connection pooling" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-PROMPT-MATCH"; then
  pass "Matching term: emits KC-PROMPT-MATCH context block"
else
  fail "Matching term: emits KC-PROMPT-MATCH context block — got: $OUTPUT"
fi
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "Matching term: includes matching item KC-0001"
else
  fail "Matching term: includes matching item KC-0001 — got: $OUTPUT"
fi
teardown

# ── Test: matching title text → emits context ───────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 2 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | discovery | Memory leak in connection pool | active | p2 | 2026-06-28 | bug |
| KC-0002 | reference | Slack webhook setup | active | p3 | 2026-06-01 | integration |
EOF
cd "$TEST_DIR"
# "memory leak" in prompt should match KC-0001 title
OUTPUT=$(echo "we have a memory leak in the auth service" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "Title match: finds item by title text"
else
  fail "Title match: finds item by title text — got: $OUTPUT"
fi
teardown

# ── Test: no match → silent exit 0 ──────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 2 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres | active | p2 | 2026-07-01 | database |
| KC-0002 | reference | Deploy checklist | active | p3 | 2026-06-01 | ops |
EOF
cd "$TEST_DIR"
# Prompt has no terms matching any item
OUTPUT=$(echo "what time is the standup tomorrow" | "$HOOK" 2>&1); RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "No match: exits 0 with no output"
else
  fail "No match: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: common words filtered out ─────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 1 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Something else entirely | active | p3 | 2026-06-01 | misc |
EOF
cd "$TEST_DIR"
# "that this with from" — all stopwords, no real terms
OUTPUT=$(echo "that this with from have are was" | "$HOOK" 2>&1); RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "Stopwords only: exits 0 with no output"
else
  fail "Stopwords only: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: empty prompt → silent exit 0 ──────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 1 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Something | active | p3 | 2026-06-01 | misc |
EOF
cd "$TEST_DIR"
OUTPUT=$(echo "" | "$HOOK" 2>&1); RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "Empty prompt: exits 0 with no output"
else
  fail "Empty prompt: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Summary ─────────────────────────────────────────────────────────

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
