#!/usr/bin/env bash
# Unit tests for kc-resurface.sh (SessionStart hook)
#
# Usage: bash test/test-kc-resurface.sh
# Run from the knowledge-curator/ directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK="$SCRIPT_DIR/../hooks/kc-resurface.sh"

PASS=0
FAIL=0

pass() { echo "  ✓ $1"; PASS=$((PASS + 1)); }
fail() { echo "  ✗ $1"; FAIL=$((FAIL + 1)); }

setup() {
  TEST_DIR=$(mktemp -d)
}

teardown() {
  rm -rf "$TEST_DIR"
}

# ── Test: no knowledge/ directory → silent exit 0 ───────────────────

setup
cd "$TEST_DIR"
if OUTPUT=$("$HOOK" 2>&1); then
  pass "No knowledge dir: exits 0 (fail-open)"
else
  fail "No knowledge dir: exits 0 (fail-open) — got: $OUTPUT"
fi
[ -z "$OUTPUT" ] && pass "No knowledge dir: produces no output"
[ -z "$OUTPUT" ] || fail "No knowledge dir: produces no output — got: $OUTPUT"
teardown

# ── Test: empty knowledge/ dir (no INDEX.md) → silent exit 0 ────────

setup
mkdir -p "$TEST_DIR/knowledge"
cd "$TEST_DIR"
if OUTPUT=$("$HOOK" 2>&1); then
  pass "Empty knowledge dir: exits 0 (fail-open)"
else
  fail "Empty knowledge dir: exits 0 (fail-open) — got: $OUTPUT"
fi
teardown

# ── Test: INDEX.md with no items → silent exit 0 ─────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 0 | 0 | 0 |
## Items
_No active items._
EOF
cd "$TEST_DIR"
if OUTPUT=$("$HOOK" 2>&1); then
  pass "Empty INDEX: exits 0"
else
  fail "Empty INDEX: exits 0 — got: $OUTPUT"
fi
[ -z "$OUTPUT" ] && pass "Empty INDEX: produces no output (no items, no p1s)"
[ -z "$OUTPUT" ] || fail "Empty INDEX: produces no output — got: $OUTPUT"
teardown

# ── Test: INDEX with p1 items → emits context ────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 5 | 2 | 1 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres | active | p1 | 2026-07-01 | database |
| KC-0002 | discovery | Memory leak found | in_progress | p1 | 2026-06-28 | bug |
| KC-0003 | lesson | Set timeouts | active | p2 | 2026-06-15 | postgres |
EOF
cd "$TEST_DIR"
OUTPUT=$("$HOOK" 2>&1)
if echo "$OUTPUT" | grep -q "KC-RESURFACE"; then
  pass "P1 items: emits KC-RESURFACE context block"
else
  fail "P1 items: emits KC-RESURFACE context block — got: $OUTPUT"
fi
if echo "$OUTPUT" | grep -q "2 p1 item"; then
  pass "P1 items: shows p1 count (2)"
else
  fail "P1 items: shows p1 count — got: $OUTPUT"
fi
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "P1 items: includes item KC-0001 in output"
else
  fail "P1 items: includes item KC-0001 — got: $OUTPUT"
fi
teardown

# ── Test: INDEX with p2-only items → emits context ──────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 3 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | lesson | Set timeouts | active | p2 | 2026-06-15 | postgres |
| KC-0002 | idea | Add caching layer | active | p2 | 2026-06-10 | performance |
| KC-0003 | reference | Linear ticket FOO-42 | active | p3 | 2026-06-01 | linear |
EOF
cd "$TEST_DIR"
OUTPUT=$("$HOOK" 2>&1)
if echo "$OUTPUT" | grep -q "KC-RESURFACE"; then
  pass "P2 items: emits context block (has items to show)"
else
  fail "P2 items: emits context block — got: $OUTPUT"
fi
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "P2 items: includes item KC-0001"
else
  fail "P2 items: includes item KC-0001 — got: $OUTPUT"
fi
teardown

# ── Test: in_progress count in output ────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat > "$TEST_DIR/knowledge/INDEX.md" << 'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 3 | 1 | 2 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | First | in_progress | p1 | 2026-07-01 | test |
| KC-0002 | idea | Second | in_progress | p2 | 2026-07-01 | test |
EOF
cd "$TEST_DIR"
OUTPUT=$("$HOOK" 2>&1)
if echo "$OUTPUT" | grep -q "2 item.* in progress"; then
  pass "In-progress: shows count (2)"
else
  fail "In-progress: shows count (2) — got: $OUTPUT"
fi
teardown

# ── Summary ─────────────────────────────────────────────────────────

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
