#!/usr/bin/env bash
# Unit tests for kc-prompt-match.sh (UserPromptSubmit hook)
#
# Usage: bash test/test-kc-prompt-match.sh
# Run from the knowledge-curator/ directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK="$SCRIPT_DIR/../hooks/kc-prompt-match.sh"

PASS=0
FAIL=0

pass() {
  echo "  ✓ $1"
  PASS=$((PASS + 1))
}
fail() {
  echo "  ✗ $1"
  FAIL=$((FAIL + 1))
}

setup() {
  TEST_DIR=$(mktemp -d)
}

teardown() {
  rm -rf "$TEST_DIR"
}

# ── Test: no knowledge/ directory → silent exit 0 ───────────────────

setup
cd "$TEST_DIR"
OUTPUT=$(echo "some query about database" | "$HOOK" 2>&1)
RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "No knowledge dir: exits 0 with no output (fail-open)"
else
  fail "No knowledge dir: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: matching term → emits context block ───────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 5 | 1 | 1 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres for primary store | active | p1 | 2026-07-01 | database, architecture |
| KC-0002 | discovery | Memory leak in connection pool | active | p1 | 2026-06-28 | bug, performance |
| KC-0003 | lesson | Always set statement_timeout | active | p2 | 2026-06-15 | postgres, reliability |
EOF
cd "$TEST_DIR"
# Prompt contains "database" which should match KC-0001's tags
OUTPUT=$(echo "how do we handle the database connection pooling" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-PROMPT-MATCH"; then
  pass "Matching term: emits KC-PROMPT-MATCH context block"
else
  fail "Matching term: emits KC-PROMPT-MATCH context block — got: $OUTPUT"
fi
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "Matching term: includes matching item KC-0001"
else
  fail "Matching term: includes matching item KC-0001 — got: $OUTPUT"
fi
teardown

# ── Test: matching title text → emits context ───────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 2 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | discovery | Memory leak in connection pool | active | p2 | 2026-06-28 | bug |
| KC-0002 | reference | Slack webhook setup | active | p3 | 2026-06-01 | integration |
EOF
cd "$TEST_DIR"
# "memory leak" in prompt should match KC-0001 title
OUTPUT=$(echo "we have a memory leak in the auth service" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "Title match: finds item by title text"
else
  fail "Title match: finds item by title text — got: $OUTPUT"
fi
teardown

# ── Test: no match → silent exit 0 ──────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 2 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres | active | p2 | 2026-07-01 | database |
| KC-0002 | reference | Deploy checklist | active | p3 | 2026-06-01 | ops |
EOF
cd "$TEST_DIR"
# Prompt has no terms matching any item
OUTPUT=$(echo "what time is the standup tomorrow" | "$HOOK" 2>&1)
RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "No match: exits 0 with no output"
else
  fail "No match: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: common words filtered out ─────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 1 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Something else entirely | active | p3 | 2026-06-01 | misc |
EOF
cd "$TEST_DIR"
# "that this with from" — all stopwords, no real terms
OUTPUT=$(echo "that this with from have are was" | "$HOOK" 2>&1)
RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "Stopwords only: exits 0 with no output"
else
  fail "Stopwords only: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: empty prompt → silent exit 0 ──────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 1 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Something | active | p3 | 2026-06-01 | misc |
EOF
cd "$TEST_DIR"
OUTPUT=$(echo "" | "$HOOK" 2>&1)
RC=$?
if [ "$RC" = "0" ] && [ -z "$OUTPUT" ]; then
  pass "Empty prompt: exits 0 with no output"
else
  fail "Empty prompt: exits 0 with no output — rc=$RC, output=$OUTPUT"
fi
teardown

# ── Test: 2-character terms match (e.g., "KC", "p1") ────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 2 | 1 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres for primary store | active | p1 | 2026-07-01 | database |
| KC-0002 | discovery | Memory leak in connection pool | active | p2 | 2026-06-28 | bug |
EOF
cd "$TEST_DIR"
# "KC" is 2 chars — should match KC-0001 and KC-0002
OUTPUT=$(echo "what is the status of KC tickets" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "2-char term: matches item by ID prefix"
else
  fail "2-char term: matches item by ID prefix — got: $OUTPUT"
fi

# "p1" is 2 chars — should match the p1 item
OUTPUT2=$(echo "show me p1 items" | "$HOOK" 2>&1) || true
if echo "$OUTPUT2" | grep -q "KC-0001"; then
  pass "2-char term: matches by priority label"
else
  fail "2-char term: matches by priority label — got: $OUTPUT2"
fi
teardown

# ── Test: max 5 total matches ────────────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 8 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Test alpha | active | p2 | 2026-07-01 | test |
| KC-0002 | idea | Test beta | active | p2 | 2026-07-01 | test |
| KC-0003 | idea | Test gamma | active | p2 | 2026-07-01 | test |
| KC-0004 | idea | Test delta | active | p2 | 2026-07-01 | test |
| KC-0005 | idea | Test epsilon | active | p2 | 2026-07-01 | test |
| KC-0006 | idea | Test zeta | active | p2 | 2026-07-01 | test |
| KC-0007 | idea | Test eta | active | p2 | 2026-07-01 | test |
| KC-0008 | idea | Test theta | active | p2 | 2026-07-01 | test |
EOF
cd "$TEST_DIR"
# "test" matches all 8 items, but only 5 should be emitted
OUTPUT=$(echo "find all test items" | "$HOOK" 2>&1) || true
COUNT=$(echo "$OUTPUT" | grep -c "^| KC-" || true)
if [ "$COUNT" -le 5 ]; then
  pass "Max matches: at most 5 items emitted (got: $COUNT)"
else
  fail "Max matches: at most 5 items emitted (got: $COUNT)"
fi
teardown

# ── Test: per-term head -3 limit ─────────────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 5 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Database tuning | active | p2 | 2026-07-01 | database |
| KC-0002 | idea | Database backup | active | p2 | 2026-07-01 | database |
| KC-0003 | idea | Database schema | active | p2 | 2026-07-01 | database |
| KC-0004 | idea | Database indexes | active | p2 | 2026-07-01 | database |
| KC-0005 | idea | Other topic | active | p2 | 2026-07-01 | other |
EOF
cd "$TEST_DIR"
# "database" matches KC-0001 through KC-0004 (4 items), but per-term cap is 3
OUTPUT=$(echo "how do we handle database configuration" | "$HOOK" 2>&1) || true
# "database" is the only term matched — should cap at 3 items
COUNT=$(echo "$OUTPUT" | grep -c "^| KC-" || true)
if [ "$COUNT" -le 3 ]; then
  pass "Per-term limit: at most 3 per search term (got: $COUNT)"
else
  fail "Per-term limit: at most 3 per search term (got: $COUNT)"
fi
teardown

# ── Test: duplicate dedup across terms ───────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 3 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | idea | Postgres connection pooling | active | p2 | 2026-07-01 | database, postgres |
| KC-0002 | discovery | Memory leak in auth | active | p2 | 2026-06-28 | bug, memory |
| KC-0003 | reference | Linear ticket FOO-42 | active | p3 | 2026-06-01 | linear |
EOF
cd "$TEST_DIR"
# "postgres" and "database" both match KC-0001 — should appear only once
OUTPUT=$(echo "postgres database performance" | "$HOOK" 2>&1) || true
COUNT=$(echo "$OUTPUT" | grep -c "KC-0001" || true)
if [ "$COUNT" -le 1 ]; then
  pass "Duplicate dedup: KC-0001 appears once despite 2 matching terms (got: $COUNT)"
else
  fail "Duplicate dedup: KC-0001 appears once despite 2 matching terms (got: $COUNT)"
fi
teardown

# ── Test: special characters in prompt ───────────────────────────────

setup
mkdir -p "$TEST_DIR/knowledge"
cat >"$TEST_DIR/knowledge/INDEX.md" <<'EOF'
# Knowledge Index
> Auto-generated by kc-index.sh.
## Summary
| Total | P1 | In Progress |
|-------|----|-------------|
| 1 | 0 | 0 |
## Items
| ID | Type | Title | Status | Priority | Updated | Tags |
|----|------|-------|--------|----------|---------|------|
| KC-0001 | decision | Use Postgres | active | p2 | 2026-07-01 | database |
EOF
cd "$TEST_DIR"
# Prompt with special characters — should still extract "postgres"
OUTPUT=$(echo "!!! what about postgres ??? @#$%^&*()" | "$HOOK" 2>&1) || true
if echo "$OUTPUT" | grep -q "KC-0001"; then
  pass "Special chars: matches despite !@#$% in prompt"
else
  fail "Special chars: matches despite !@#$% in prompt — got: $OUTPUT"
fi
teardown

# ── Summary ─────────────────────────────────────────────────────────

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
