#!/usr/bin/env bash
# prescan-wire-claude-md.sh — deterministic CLAUDE.md managed-block injection.
# Inserts or replaces the <!-- ticket-auto:agent-knowledge --> block in a repo's
# CLAUDE.md. Zero LLM involvement — replaces the fragile "LLM writes sed" pattern.
# Idempotent: running twice produces the same result.
set -eo pipefail

# ── Usage ─────────────────────────────────────────────────────────────────────

usage() {
  cat >&2 <<'EOF'
Usage: prescan-wire-claude-md.sh --claude-md <path> --prescan-index <path> [--repo-slug <slug>]

Inserts or replaces a managed block in CLAUDE.md pointing to prescan docs.
If the START/END markers exist, content between them is replaced.
If they don't exist, the block is appended at the end of the file.

Options:
  --claude-md <path>     Path to the repo's CLAUDE.md
  --prescan-index <path> Path to the prescan INDEX.md for this repo
  --repo-slug <slug>     Repo slug (optional, derived from path if omitted)
  --dry-run              Print what would be done, don't modify files

Exit: 0 on success, 1 if CLAUDE.md not found, 2 on write error
EOF
  exit 2
}

# ── Block content ──────────────────────────────────────────────────────────────

START_MARKER="<!-- ticket-auto:agent-knowledge START -->"
END_MARKER="<!-- ticket-auto:agent-knowledge END -->"

_build_block() {
  local index_path="$1" slug="${2:-}"
  local docs_dir
  docs_dir=$(dirname "$index_path")
  local repos_root
  repos_root=$(dirname "$(dirname "$docs_dir")")

  cat <<BLOCKEOF
$START_MARKER
## Agent Knowledge

Pre-built agent-knowledge docs are at \`.ticket-auto/$slug/docs/\`.
See the [Prescan Index]($index_path) for topic and service lookup tables,
or [Overview]($docs_dir/overview.md) for architecture overview.

These files are machine-generated by \`/ticket-prescan\`. Do not edit manually.
$END_MARKER
BLOCKEOF
}

# ── Main ───────────────────────────────────────────────────────────────────────

main() {
  local claude_md="" index_path="" slug="" dry_run="false"

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --claude-md)      claude_md="${2:-}"; shift 2 ;;
    --prescan-index)  index_path="${2:-}"; shift 2 ;;
    --repo-slug)      slug="${2:-}"; shift 2 ;;
    --dry-run)        dry_run="true"; shift ;;
    --help|-h)        usage ;;
    *) echo "Unknown flag: $1" >&2; usage ;;
    esac
  done

  [ -z "$claude_md" ] && { echo "ERROR: --claude-md is required" >&2; usage; }
  [ -z "$index_path" ] && { echo "ERROR: --prescan-index is required" >&2; usage; }

  if [ ! -f "$claude_md" ]; then
    echo "ERROR: CLAUDE.md not found: $claude_md" >&2
    exit 1
  fi

  if [ -z "$slug" ]; then
    slug=$(basename "$(dirname "$(dirname "$index_path")")")
  fi

  local block_text
  block_text=$(_build_block "$index_path" "$slug")
  local tmp="${claude_md}.tmp.$$"

  if grep -qF "$START_MARKER" "$claude_md" 2>/dev/null; then
    # Markers exist — replace content between them
    if [ "$dry_run" = "true" ]; then
      echo "[dry-run] Would replace managed block in $claude_md"
      echo "$block_text"
      return 0
    fi
    # Use awk for multi-line replacement between markers
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block_text" '
      BEGIN { in_block = 0 }
      $0 == start { print block; in_block = 1; next }
      $0 == end   { in_block = 0; next }
      !in_block   { print }
    ' "$claude_md" > "$tmp" && mv "$tmp" "$claude_md"
  else
    # No markers — append block at end
    if [ "$dry_run" = "true" ]; then
      echo "[dry-run] Would append managed block to $claude_md"
      echo "$block_text"
      return 0
    fi
    cp "$claude_md" "$tmp"
    echo "" >> "$tmp"
    echo "$block_text" >> "$tmp"
    mv "$tmp" "$claude_md"
  fi

  echo "PRESCAN_WIRE_STATUS=done"
  echo "PRESCAN_WIRE_FILE=$claude_md"
}

# ── Dispatch ───────────────────────────────────────────────────────────────────

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
