#!/usr/bin/env bash
# Shared agent spawn helpers. Source this file from the ticket-auto orchestrator.
# These functions handle the repeatable boilerplate around agent spawns —
# logging, heartbeat pinger, phase context file, and result capture.
set -euo pipefail

# Source heartbeat library (provides hb_* and cl_write) unless already loaded (e.g. test mocks)
if ! declare -f hb_heartbeat >/dev/null 2>&1; then
  _HB_LIB="$(dirname "${BASH_SOURCE[0]}")/heartbeat.sh"
  [ -f "$_HB_LIB" ] && source "$_HB_LIB"
fi

# ── spawn_write_env ──────────────────────────────────────────────────────────────
# Write extracted CLAUDE.md fields to /tmp/ticket-auto-{TICKET_ID}-env.sh using
# single-quote heredoc that prevents shell interpretation. Sub-agents source this
# file to get project context without reading CLAUDE.md independently.
#
# Usage: spawn_write_env TICKET_ID=<id> \
#          REPOS_ROOT=<path> ISSUE_PREFIX=<prefix> BE_SERVICES=<services> \
#          [WIKI_ROOT=<path>] [BE_TEST_CMD=<cmd>] [FE_TEST_CMD=<cmd>] \
#          [LOCAL_URL=<url>] [UAT_URL=<url>] [SLACK_CHANNEL=<channel>]
#
# Uses single-quote heredoc — no shell expansion, no injection risk.
spawn_write_env() {
  local TICKET_ID=""
  local REPOS_ROOT=""
  local ISSUE_PREFIX=""
  local BE_SERVICES=""
  local WIKI_ROOT=""
  local BE_TEST_CMD=""
  local FE_TEST_CMD=""
  local LOCAL_URL=""
  local UAT_URL=""
  local SLACK_CHANNEL=""

  # Parse named parameters
  for arg in "$@"; do
    case "$arg" in
    TICKET_ID=*) TICKET_ID="${arg#TICKET_ID=}" ;;
    REPOS_ROOT=*) REPOS_ROOT="${arg#REPOS_ROOT=}" ;;
    ISSUE_PREFIX=*) ISSUE_PREFIX="${arg#ISSUE_PREFIX=}" ;;
    BE_SERVICES=*) BE_SERVICES="${arg#BE_SERVICES=}" ;;
    WIKI_ROOT=*) WIKI_ROOT="${arg#WIKI_ROOT=}" ;;
    BE_TEST_CMD=*) BE_TEST_CMD="${arg#BE_TEST_CMD=}" ;;
    FE_TEST_CMD=*) FE_TEST_CMD="${arg#FE_TEST_CMD=}" ;;
    LOCAL_URL=*) LOCAL_URL="${arg#LOCAL_URL=}" ;;
    UAT_URL=*) UAT_URL="${arg#UAT_URL=}" ;;
    SLACK_CHANNEL=*) SLACK_CHANNEL="${arg#SLACK_CHANNEL=}" ;;
    *)
      echo "spawn_write_env: unknown parameter '$arg'" >&2
      return 1
      ;;
    esac
  done

  if [ -z "$TICKET_ID" ]; then
    echo "spawn_write_env: TICKET_ID is required" >&2
    return 1
  fi

  local env_file="/tmp/ticket-auto-${TICKET_ID}-env.sh"

  # Single-quote heredoc — NO shell expansion, NO injection.
  # Even BE_TEST_CMD="mvn test -Dfoo=\"bar\"" is preserved exactly.
  cat >"$env_file" <<'ENVEOF'
#!/usr/bin/env bash
# Auto-generated by spawn-helper.sh — do not edit by hand.
# Sourced by --from-auto sub-agents to get project context without reading CLAUDE.md.
# Regenerated fresh each pipeline run by the orchestrator's Step 0.5.
export TICKET_ID="TICKET_ID_PLACEHOLDER"
export REPOS_ROOT="REPOS_ROOT_PLACEHOLDER"
export ISSUE_PREFIX="ISSUE_PREFIX_PLACEHOLDER"
export BE_SERVICES="BE_SERVICES_PLACEHOLDER"
export WIKI_ROOT="WIKI_ROOT_PLACEHOLDER"
export BE_TEST_CMD="BE_TEST_CMD_PLACEHOLDER"
export FE_TEST_CMD="FE_TEST_CMD_PLACEHOLDER"
export LOCAL_URL="LOCAL_URL_PLACEHOLDER"
export UAT_URL="UAT_URL_PLACEHOLDER"
export SLACK_CHANNEL="SLACK_CHANNEL_PLACEHOLDER"
ENVEOF

  # Sed-replace placeholders with actual values (escaped for sed)
  # Values may contain / & \ but sed delimiter is |, so only | needs escaping
  _sed_escape() { echo "$1" | sed 's/|/\\|/g'; }

  sed -i \
    -e "s|TICKET_ID_PLACEHOLDER|$(_sed_escape "$TICKET_ID")|" \
    -e "s|REPOS_ROOT_PLACEHOLDER|$(_sed_escape "$REPOS_ROOT")|" \
    -e "s|ISSUE_PREFIX_PLACEHOLDER|$(_sed_escape "$ISSUE_PREFIX")|" \
    -e "s|BE_SERVICES_PLACEHOLDER|$(_sed_escape "$BE_SERVICES")|" \
    -e "s|WIKI_ROOT_PLACEHOLDER|$(_sed_escape "$WIKI_ROOT")|" \
    -e "s|BE_TEST_CMD_PLACEHOLDER|$(_sed_escape "$BE_TEST_CMD")|" \
    -e "s|FE_TEST_CMD_PLACEHOLDER|$(_sed_escape "$FE_TEST_CMD")|" \
    -e "s|LOCAL_URL_PLACEHOLDER|$(_sed_escape "$LOCAL_URL")|" \
    -e "s|UAT_URL_PLACEHOLDER|$(_sed_escape "$UAT_URL")|" \
    -e "s|SLACK_CHANNEL_PLACEHOLDER|$(_sed_escape "$SLACK_CHANNEL")|" \
    "$env_file"

  # Auto-append LINEAR_API_KEY to env file when available
  if [ -n "${LINEAR_API_KEY:-}" ]; then
    echo "export LINEAR_API_KEY=\"${LINEAR_API_KEY}\"" >>"$env_file"
  fi

  # Restrict permissions — env file may contain credentials
  chmod 600 "$env_file"

  echo "spawn_write_env: wrote $env_file"

  return 0
}

# ── spawn_agent_pre ──────────────────────────────────────────────────────────────
# Pre-spawn boilerplate: writes the waiting log entry, starts the heartbeat pinger,
# and writes the phase context file. The orchestrator reads the printed "AGENT_PROMPT"
# line and spawns the agent with that prompt.
#
# Usage: spawn_agent_pre PHASE=<phase> STEP=<step> LOG_FILE=<path> \
#          HB_LOG_FILE=<path> CLAUDE_LOG_FILE=<path> TICKET_ID=<id> \
#          SKILL=<skill> [FLAGS=<flags>] [INSTRUCTIONS=<instructions>] \
#          [DESCRIPTION=<desc>] [FROM_STEP=<step>]
#
# Prints to stdout:
#   AGENT_PROMPT=<the full agent spawn prompt>
# The orchestrator reads this and passes it to the Agent tool.
spawn_agent_pre() {
  local PHASE=""
  local STEP=""
  local LOG_FILE=""
  local HB_LOG_FILE=""
  local CLAUDE_LOG_FILE=""
  local TICKET_ID=""
  local SKILL=""
  local FLAGS="--from-auto"
  local INSTRUCTIONS="Follow the skill exactly. Report only the final handoff output."
  local DESCRIPTION=""
  local FROM_STEP=""

  for arg in "$@"; do
    case "$arg" in
    PHASE=*) PHASE="${arg#PHASE=}" ;;
    STEP=*) STEP="${arg#STEP=}" ;;
    LOG_FILE=*) LOG_FILE="${arg#LOG_FILE=}" ;;
    HB_LOG_FILE=*) HB_LOG_FILE="${arg#HB_LOG_FILE=}" ;;
    CLAUDE_LOG_FILE=*) CLAUDE_LOG_FILE="${arg#CLAUDE_LOG_FILE=}" ;;
    TICKET_ID=*) TICKET_ID="${arg#TICKET_ID=}" ;;
    SKILL=*) SKILL="${arg#SKILL=}" ;;
    FLAGS=*) FLAGS="${arg#FLAGS=}" ;;
    INSTRUCTIONS=*) INSTRUCTIONS="${arg#INSTRUCTIONS=}" ;;
    DESCRIPTION=*) DESCRIPTION="${arg#DESCRIPTION=}" ;;
    FROM_STEP=*) FROM_STEP="${arg#FROM_STEP=}" ;;
    *)
      echo "spawn_agent_pre: unknown parameter '$arg'" >&2
      return 1
      ;;
    esac
  done

  # Validate required params
  local missing=""
  [ -z "$PHASE" ] && missing="$missing PHASE"
  [ -z "$STEP" ] && missing="$missing STEP"
  [ -z "$TICKET_ID" ] && missing="$missing TICKET_ID"
  [ -z "$SKILL" ] && missing="$missing SKILL"
  if [ -n "$missing" ]; then
    echo "spawn_agent_pre: missing required parameters:$missing" >&2
    return 1
  fi

  # If FROM_STEP is set, append to FLAGS
  if [ -n "$FROM_STEP" ]; then
    FLAGS="$FLAGS --from-step $FROM_STEP"
  fi

  # F10 race-window guard: clear stale stop files from prior phases, then
  # check for external kill signals from the fleet controller.
  # spawn_agent_post() creates pinger and watchdog stop files during normal
  # cleanup (hb_pinger_stop, spawn_watchdog_stop). On the next phase, those
  # stale files would cause a false abort. Remove them first so only files
  # created AFTER this point (genuine fleet kills) trigger the guard.
  local _pinger_stop="/tmp/ticket-auto-${TICKET_ID}-pinger-stop"
  local _watchdog_stop="/tmp/ticket-auto-${TICKET_ID}-watchdog-stop"
  rm -f "$_pinger_stop" "$_watchdog_stop"
  # Yield to widen the race-window guard enough for fleet controller signals
  # to land. The fleet controller polls every 30s — 1ms is invisible to
  # pipeline throughput but makes the window testable.
  sleep 0.01 2>/dev/null || true
  if [ -f "$_pinger_stop" ]; then
    echo "spawn_agent_pre: spawn aborted — external kill detected for ${TICKET_ID}" >&2
    return 1
  fi

  local phase_lower
  phase_lower=$(echo "$STEP" | tr '[:upper:]' '[:lower:]')

  # 1. Write waiting log entry (idempotent: skip if last line already matches)
  if [ -n "$LOG_FILE" ]; then
    local last_line
    last_line=$(tail -1 "$LOG_FILE" 2>/dev/null || true)
    if echo "$last_line" | grep -q "|${PHASE}|${phase_lower}|waiting|"; then
      : # already written, skip
    else
      local desc="${DESCRIPTION:-agent for ${TICKET_ID}}"
      echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)|${PHASE}|${phase_lower}|waiting|Agent launched — ${desc}" >>"$LOG_FILE"
    fi
  fi

  # 2. Start heartbeat pinger and watchdog
  local PINGER_PID=""
  local WATCHDOG_PID=""
  if [ -n "${HB_LOG_FILE:-}" ]; then
    local pinger_stop="/tmp/ticket-auto-${TICKET_ID}-pinger-stop"
    local watchdog_stop="/tmp/ticket-auto-${TICKET_ID}-watchdog-stop"
    export HB_LOG_FILE="$HB_LOG_FILE"
    hb_heartbeat "orchestrator-waiting" "agent ${phase_lower} launched"
    hb_pinger_start "$pinger_stop"
    PINGER_PID=$!
    spawn_watchdog_start "$watchdog_stop" "$PHASE"
    WATCHDOG_PID=$!
  fi

  # 3. Write phase context file
  if [ -n "$LOG_FILE" ]; then
    echo "${PHASE}|${LOG_FILE}" >"/tmp/ticket-auto-${TICKET_ID}-ctx.txt"
  fi

  # 4. Write cl_write handoff
  if [ -n "${CLAUDE_LOG_FILE:-}" ]; then
    local from_info="${FROM_STEP:-fresh}"
    cl_write "$PHASE" "handoff" "info" "ticket=${TICKET_ID} from_step=${from_info}"
  fi

  # 5. Print the agent spawn prompt for the orchestrator to forward
  # Build the env-sourcing prefix. printf '%q' escapes shell metacharacters
  # in path values, preventing command injection if a path contains ";", $(), etc.
  local _q
  _q() { printf '%q' "$1"; }
  local env_prefix="export LOG_FILE=$(_q "${LOG_FILE}"); export HB_LOG_FILE=$(_q "${HB_LOG_FILE}"); export CLAUDE_LOG_FILE=$(_q "${CLAUDE_LOG_FILE}"); source ~/.claude/skills/lib/heartbeat.sh; source /tmp/ticket-auto-$(_q "${TICKET_ID}")-env.sh"

  echo "AGENT_PROMPT=Run ${SKILL} ${TICKET_ID} ${FLAGS}. Before starting, run: ${env_prefix}. ${INSTRUCTIONS}"

  # 6. Store spawn metadata for spawn_agent_post
  local meta_file="/tmp/ticket-auto-${TICKET_ID}-spawn-meta.txt"
  cat >"$meta_file" <<EOF
PHASE=$PHASE
STEP=$STEP
TICKET_ID=$TICKET_ID
LOG_FILE=$LOG_FILE
HB_LOG_FILE=$HB_LOG_FILE
CLAUDE_LOG_FILE=$CLAUDE_LOG_FILE
PINGER_PID=$PINGER_PID
WATCHDOG_PID=$WATCHDOG_PID
EOF

  return 0
}

# ── spawn_agent_post ─────────────────────────────────────────────────────────────
# Post-spawn boilerplate: stops the heartbeat pinger and writes the done or fail
# log entry. Call this after the agent returns.
#
# Usage: spawn_agent_post TICKET_ID=<id> RESULT=<done|fail> [MSG=<message>] \
#          [NEXT_PHASE=<phase>] [PHASE=<phase>] [STEP=<step>]
#
# Or, after calling spawn_agent_pre, the metadata file is auto-read:
# Usage: spawn_agent_post TICKET_ID=<id> RESULT=<done|fail> [MSG=<message>] \
#          [NEXT_PHASE=<phase>]
spawn_agent_post() {
  local TICKET_ID=""
  local RESULT=""
  local MSG=""
  local NEXT_PHASE=""
  local PHASE=""
  local STEP=""
  local LOG_FILE=""
  local HB_LOG_FILE=""
  local CLAUDE_LOG_FILE=""

  for arg in "$@"; do
    case "$arg" in
    TICKET_ID=*) TICKET_ID="${arg#TICKET_ID=}" ;;
    RESULT=*) RESULT="${arg#RESULT=}" ;;
    MSG=*) MSG="${arg#MSG=}" ;;
    NEXT_PHASE=*) NEXT_PHASE="${arg#NEXT_PHASE=}" ;;
    PHASE=*) PHASE="${arg#PHASE=}" ;;
    STEP=*) STEP="${arg#STEP=}" ;;
    LOG_FILE=*) LOG_FILE="${arg#LOG_FILE=}" ;;
    HB_LOG_FILE=*) HB_LOG_FILE="${arg#HB_LOG_FILE=}" ;;
    CLAUDE_LOG_FILE=*) CLAUDE_LOG_FILE="${arg#CLAUDE_LOG_FILE=}" ;;
    *)
      echo "spawn_agent_post: unknown parameter '$arg'" >&2
      return 1
      ;;
    esac
  done

  # If metadata file exists and explicit params not given, read from it
  local meta_file="/tmp/ticket-auto-${TICKET_ID}-spawn-meta.txt"
  local PINGER_PID=""
  local WATCHDOG_PID=""
  if [ -f "$meta_file" ] && [ -z "$PHASE" ]; then
    while IFS='=' read -r key val; do
      case "$key" in
      PHASE) [ -z "$PHASE" ] && PHASE="$val" ;;
      STEP) [ -z "$STEP" ] && STEP="$val" ;;
      LOG_FILE) [ -z "$LOG_FILE" ] && LOG_FILE="$val" ;;
      HB_LOG_FILE) [ -z "$HB_LOG_FILE" ] && HB_LOG_FILE="$val" ;;
      CLAUDE_LOG_FILE) [ -z "$CLAUDE_LOG_FILE" ] && CLAUDE_LOG_FILE="$val" ;;
      PINGER_PID) [ -z "$PINGER_PID" ] && PINGER_PID="$val" ;;
      WATCHDOG_PID) [ -z "$WATCHDOG_PID" ] && WATCHDOG_PID="$val" ;;
      esac
    done <"$meta_file"
  fi

  if [ -z "$TICKET_ID" ] || [ -z "$RESULT" ]; then
    echo "spawn_agent_post: TICKET_ID and RESULT are required" >&2
    return 1
  fi

  local phase_lower=""
  [ -n "${STEP:-}" ] && phase_lower=$(echo "${STEP:-}" | tr '[:upper:]' '[:lower:]')

  # Stop watchdog and heartbeat pinger
  if [ -n "${HB_LOG_FILE:-}" ]; then
    local watchdog_stop="/tmp/ticket-auto-${TICKET_ID}-watchdog-stop"
    local pinger_stop="/tmp/ticket-auto-${TICKET_ID}-pinger-stop"
    spawn_watchdog_stop "$watchdog_stop"
    hb_pinger_stop "$pinger_stop"

    # Reap background processes — wait for captured PIDs to prevent zombie accumulation.
    # Handles stale PIDs (process already exited): wait on dead PID returns immediately
    # with exit 127, which is acceptable (non-fatal, logged to stderr only in debug).
    if [ -n "$PINGER_PID" ] || [ -n "$WATCHDOG_PID" ]; then
      local _pid _waited=0
      for _pid in "$PINGER_PID" "$WATCHDOG_PID"; do
        [ -z "$_pid" ] && continue
        wait "$_pid" 2>/dev/null &
        local _wait_pid=$!
        # 5-second timeout per PID
        local _timeout=50
        while [ "$_timeout" -gt 0 ] && kill -0 "$_wait_pid" 2>/dev/null; do
          sleep 0.1
          _timeout=$((_timeout - 1))
        done
        kill -0 "$_wait_pid" 2>/dev/null && kill "$_wait_pid" 2>/dev/null || true
        _waited=1
      done
      # Suppress shell's "Terminated" messages for killed wait jobs
      [ "$_waited" -eq 1 ] && wait 2>/dev/null || true
    else
      # Fallback: no PID capture available — wait for any child with 5-second total timeout
      local _waited=0
      while [ "$_waited" -lt 50 ]; do
        wait -n 2>/dev/null && break || break
        _waited=$((_waited + 1))
        sleep 0.1
      done
    fi
  fi

  case "$RESULT" in
  done)
    if [ -n "${LOG_FILE:-}" ]; then
      local done_msg="${MSG:-agent done}"
      local last_line
      last_line=$(tail -1 "${LOG_FILE}" 2>/dev/null || true)
      if echo "$last_line" | grep -q "|${PHASE:-UNKNOWN}|${phase_lower:-unknown}|done|"; then
        : # already written, skip
      else
        echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)|${PHASE:-UNKNOWN}|${phase_lower:-unknown}|done|${done_msg}" >>"$LOG_FILE"
      fi
    fi
    if [ -n "${HB_LOG_FILE:-}" ]; then
      hb_heartbeat "agent-returned" "${phase_lower:-agent} done — ${MSG:-}"
      if [ -n "$NEXT_PHASE" ]; then
        hb_heartbeat "phase-transition" "${PHASE:-} → ${NEXT_PHASE}"
      fi
    fi
    if [ -n "${CLAUDE_LOG_FILE:-}" ]; then
      cl_write "${PHASE:-UNKNOWN}" "${phase_lower:-unknown}" "done" "${MSG:-agent done}"
    fi
    ;;

  fail)
    local fail_msg="${MSG:-Agent failed}"
    local fail_action="${FAIL_ACTION:-stop}"
    local suffix=""
    [ "$fail_action" = "warn-continue" ] && suffix=" — continuing"

    if [ -n "${LOG_FILE:-}" ]; then
      local last_line
      last_line=$(tail -1 "${LOG_FILE}" 2>/dev/null || true)
      if echo "$last_line" | grep -q "|${PHASE:-UNKNOWN}|${phase_lower:-unknown}|fail|"; then
        : # already written, skip
      else
        echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)|${PHASE:-UNKNOWN}|${phase_lower:-unknown}|fail|${fail_msg}${suffix}" >>"$LOG_FILE"
      fi
    fi
    if [ -n "${HB_LOG_FILE:-}" ]; then
      hb_heartbeat "agent-returned" "${phase_lower:-agent} failed${suffix}"
    fi
    if [ -n "${CLAUDE_LOG_FILE:-}" ]; then
      local last_hb="unknown"
      [ -n "${HB_LOG_FILE:-}" ] && [ -f "$HB_LOG_FILE" ] && last_hb=$(tail -1 "$HB_LOG_FILE" 2>/dev/null | cut -d'|' -f2-4 || echo "unknown")
      cl_write "${PHASE:-UNKNOWN}" "context" "fail" "${phase_lower:-agent} agent failed (${fail_action}) — last_hb: ${last_hb}"
      if [ "$fail_action" = "stop" ]; then
        cl_write RETRO hint info "sub-agent spawn failure in ${PHASE:-UNKNOWN} phase — check agent isolation, tool availability, and CLAUDE_LOG_FILE export for diagnostics"
      fi
    fi
    ;;

  *)
    echo "spawn_agent_post: RESULT must be 'done' or 'fail', got '$RESULT'" >&2
    return 1
    ;;
  esac

  # Meta file persists until next spawn_agent_pre overwrites it.
  # This allows duplicate spawn_agent_post calls to read PHASE/STEP
  # for idempotency guard tail-checks.

  return 0
}

# ── spawn_capture ────────────────────────────────────────────────────────────────
# Wrapper around capture_agent_result that reads metadata if available.
# Usage: spawn_capture TICKET_ID=<id> PHASE=<phase> RESULT="<agent output>"
spawn_capture() {
  local TICKET_ID=""
  local PHASE=""
  local RESULT=""
  local ATTEMPT=""

  for arg in "$@"; do
    case "$arg" in
    TICKET_ID=*) TICKET_ID="${arg#TICKET_ID=}" ;;
    PHASE=*) PHASE="${arg#PHASE=}" ;;
    RESULT=*) RESULT="${arg#RESULT=}" ;;
    ATTEMPT=*) ATTEMPT="${arg#ATTEMPT=}" ;;
    *)
      echo "spawn_capture: unknown parameter '$arg'" >&2
      return 1
      ;;
    esac
  done

  if [ -z "$TICKET_ID" ] || [ -z "$PHASE" ]; then
    echo "spawn_capture: TICKET_ID and PHASE are required" >&2
    return 1
  fi

  if [ -n "${ATTEMPT:-}" ]; then
    capture_agent_result "$TICKET_ID" "$PHASE" "${RESULT:-}" "$ATTEMPT"
  else
    capture_agent_result "$TICKET_ID" "$PHASE" "${RESULT:-}"
  fi
}

# ── spawn_watchdog_start ─────────────────────────────────────────────────────────
# Backgrounds a watchdog heartbeat loop that emits hb_heartbeat entries every 60s
# while the orchestrator waits for a sub-agent. Uses a stop-file to signal shutdown.
#
# Usage: spawn_watchdog_start <stop_file> <phase_label> [sleep_secs=60]
spawn_watchdog_start() {
  [ -z "${HB_LOG_FILE:-}" ] && return 0

  local stop_file="$1"
  local phase_label="${2:-unknown}"
  local sleep_secs="${3:-60}"

  rm -f "$stop_file"

  (
    set +e
    while true; do
      sleep "$sleep_secs"
      [ -f "$stop_file" ] && break
      hb_heartbeat "watchdog" "alive" "waiting for ${phase_label} agent" || true
    done
  ) >/dev/null 2>&1 &
  disown
}

# ── spawn_watchdog_stop ──────────────────────────────────────────────────────────
# Stops the watchdog background process by creating its stop file.
# Args: stop_file
spawn_watchdog_stop() {
  [ -z "${HB_LOG_FILE:-}" ] && return 0
  touch "$1"
}
